name: Deploy Frontend to Firebase

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**' # Chỉ chạy khi có thay đổi ở frontend
  workflow_dispatch: # Cho phép kích hoạt thủ công từ giao diện GitHub

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build
        env:
          VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL }}
          VITE_SOCKET_URL: ${{ vars.VITE_SOCKET_URL }}

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_TOKEN }}'
          projectId: chat-app-it4409-168509-new
          channelId: live